apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-swarm-ingress
  namespace: hospital-swarm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  tls:
    - hosts:
        - app.hospital-swarm.com
        - api.hospital-swarm.com
      secretName: hospital-swarm-tls
  rules:
    - host: app.hospital-swarm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hospital-swarm-frontend-service
                port:
                  number: 80
    - host: api.hospital-swarm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hospital-swarm-backend-service
                port:
                  number: 80
